export const books = [
  {
    'no.': 26,
    book_seq: 26,
    series_seq: 7,
    book_code: 'LSR001',
    book_name: 'The Muffin Man',
    book_img: '/datafiles/books/LSR001.jpg',
    book_level: 'Level K',
    level_seq: -1,
    cefr: 'pre A1',
    lexile: '110L',
    author: 'Kelly Daniels',
    total_page: 15,
    total_sentence: 6,
    word_count: 30,
    learn: true,
    checkup: true,
    record: false
  },
  {
    'no.': 138,
    book_seq: 536,
    series_seq: 12,
    book_code: 'SRT001',
    book_name: 'Good for You',
    book_img: '/datafiles/books/SRT001.jpg',
    book_level: 'Level Starter',
    level_seq: 0,
    cefr: 'A1',
    lexile: '',
    author: 'Joy Cowley',
    total_page: 16,
    total_sentence: 8,
    word_count: 0,
    learn: true,
    checkup: true,
    record: true
  },
  {
    'no.': 200,
    book_seq: 356,
    series_seq: 8,
    book_code: 'MFC001',
    book_name: 'The Ugly Duckling',
    book_img: '/datafiles/books/MFC001.jpg',
    book_level: 'Level 1',
    level_seq: 1,
    cefr: 'A1/A2',
    lexile: '300L',
    author: 'HC Andersen',
    total_page: 20,
    total_sentence: 19,
    word_count: 114,
    learn: true,
    checkup: true,
    record: true
  },
  {
    'no.': 338,
    book_seq: 200,
    series_seq: 1,
    book_code: 'ECR081',
    book_name: 'Puss in Boots',
    book_img: '/datafiles/books/ECR081.jpg',
    book_level: 'Level 4',
    level_seq: 4,
    cefr: 'A1/A2',
    lexile: '440L',
    author: 'Charles Perrault',
    total_page: 12,
    total_sentence: 96,
    word_count: 828,
    learn: true,
    checkup: true,
    record: true
  }
]
